namespace EmbeddedLuaCode
{
    const char* const constantsPeds = R"~LUA~(
--[[
    SERVER AND CLIENT.
    Defines a constant variables available for server and client.
--]]

constants.PedStats = setmetatable({
    ProgressMade = 0,
    TotalProgress = 1,
    LongestBasketball = 2,
    -- Distances
    DistanceFoot = 3,
    DistanceCar = 4,
    DistanceBike = 5,
    DistanceBoat = 6,
    DistanceGolfCart = 7,
    DistanceHelicopter = 8,
    DistancePlane = 9,
    LongestWheelieDistance = 10,
    LongestStoppieDistance = 11,
    Longest2WheelDistance = 12,
    DistanceSwimming = 26,
    DistanceCycle = 27,
    DistanceTreadmill = 28,
    DistanceExcersiseBike = 29,
    MaxJumpDistance = 139,
    -- Cash
    WeaponBudget = 13,
    FashionBudget = 14,
    PropertyBudget = 15,
    SprayingBudget = 16,
    FoodBudget = 20,
    TattooBudget = 30,
    HairdressingBudget = 31,
    ProstituteBudget = 33,
    StripClubBudget = 54,
    CarModBudget = 55,
    TotalShoppingBudget = 62,
    -- Times
    LongestWheelieTime = 17,
    LongestStoppieTime = 18,
    Longest2WheelTime = 19,
    LongestTreadmillTime = 44,
    LongestExcersiseBikeTime = 45,
    BestTimeHotring = 48,
    BestTimeBmx = 49,
    LongestChaseTime = 51,
    LastChaseTime = 52,
    TimeSpentShopping = 56,
    TimeSpentUnderwater = 63,
    FlightTime = 169,
    FlightTimeJetpack = 173,
    -- Body
    Fat = 21,
    Stamina = 22,
    Muscle = 23,
    MaxHealth = 24,
    SexAppeal = 25,
    -- Gambling
    MoneySpentGambling = 35,
    MoneyMadePimping = 36,
    MoneyWonGambling = 37,
    BiggestGamblingWin = 38,
    BiggestGamblingLoss = 39,
    Gambling = 81,
    -- Respect
    RespectTotal = 64,
    RespectGirlFriend= 65,
    RespectClothed = 66,
    RespectFitness = 67,
    Respect = 68,
    -- Weapon
    WeaponPistolSkill = 69,
    WeaponPistolSilencedSkill = 70,
    WeaponDeagleSkill = 71,
    WeaponShotgunSkill = 72,
    WeaponSawnoffSkill = 73,
    WeaponSpas12Skill = 74,
    WeaponUZISkill = 75,
    WeaponMP5Skill = 76,
    WeaponAK47Skill = 77,
    WeaponM4Skill = 78,
    WeaponSniperSkill = 79,
    -- Other
    LargestBurglarySwag = 40,
    MoneyMadeBurglary = 41,
    HeaviestWeightBenchPress = 46,
    HeaviestWeightDumbells = 47,
    WageBill = 53,
    SexAppealClothes = 80,
    PeopleKilledByOthers = 120,
    PeopleKilledByPlayer = 121,
    CarsDestroyed = 122,
    BoatsDestroyed = 123,
    HelicoptersDestroyed = 124,
    PropertyDestroyed = 125,
    RoundsFired = 126,
    ExplosivesUsed = 127,
    BulletsHit = 128,
    TyresPopped = 129,
    HeadsPopped = 130,
    WantedStarsAttained = 131,
    WantedStarsEvaded = 132,
    TimesArrested = 133,
    DaysPassed = 134,
    TimesDied = 135,
    TimesSaved = 136,
    TimesCheated = 137,
    Sprayings = 138,
    MaxJumpHeight = 140,
    MaxJumpFlips = 141,
    MaxJumpSpins = 142,
    BestStunt = 143,
    UniqueJumpsFound = 144,
    UniqueJumpsDone = 145,
    MissionsAttempted = 146,
    MissionsPassed = 147,
    TotalMissions = 148,
    TaxiMoneyMade = 149,
    PassengersDeliveredInTaxi = 150,
    LivesSaved = 151,
    CriminalsCaught = 152,
    FiresExtinguished = 153,
    PizzasDelivered = 154,
    Assassinations = 155,
    LatestDanceScore = 156,
    VigilanteLevel = 157,
    AmbulanceLevel = 158,
    FirefighterLevel = 159,
    DrivingSkill = 160,
    TruckMissionsPassed = 161,
    TruckMoneyMade = 162,
    RecruitedGangMembersKilled = 163,
    Armour = 164,
    Energy = 165,
    PhotosTaken = 166,
    KillFrenziesAttempted = 167,
    KillFrenziesPassed = 168,
    TimesDrowned = 170,
    GirlsPimped = 171,
    BestPositionHotring = 172,
    ShootingRangeScore = 174,
    ValetCarsParked = 175,
    KillsSinceLastCheckpoint = 176,
    TotalLegitimateKills = 177,
    BloodringKills = 178,
    BloodringTime = 179,
    NoMoreHurricanes = 180,
    CitiesPassed = 181,
    PoliceBribes = 182,
    CarsStolen = 183,
    CurrentGirlfriends = 184,
    BadDates = 185,
    GirlsDated = 186,
    TimesScoredWithGirl = 187,
    Dates = 188,
    GirlsDumped = 189,
    TimesVisitedProstitute = 190,
    HousesBurgled = 191,
    SafesCracked = 192,
    StolenItemsSold = 194,
    EightballsInPool = 195,
    WinsInPool = 196,
    LossesInPool = 197,
    VisitsToGym = 198,
    MealsEaten = 200,
    UnderwaterStamina = 225,
    BikeSkill = 229,
    CycleSkill = 230,
}, __readonly_table_meta__)

constants.PedWalkingStyle = setmetatable({
    Default = 0,
    Player = 54,
    PlayerFat = 55,
    PlayerMuscular = 56,
    RocketLauncher = 57,
    RocketLauncherFat = 58,
    RocketLauncherMuscular = 59,
    Armed = 60,
    ArmedFat = 61,
    ArmedMuscular = 62,
    BaseballBat = 63,
    BaseballBatFat = 64,
    BaseballBatMuscular = 65,
    Chainsaw = 66,
    ChainsawFat = 67,
    ChainsawMuscular = 68,
    Sneak = 69,
    Jetpack = 70,
    Man = 118,
    Shuffle = 119,
    OldMan = 120,
    Gang1 = 121,
    Gang2 = 122,
    OldFatMan = 123,
    FatMan = 124,
    Jogger = 125,
    DrunkMan = 126,
    BlindMan = 127,
    Swat = 128,
    Woman = 129,
    Shopping = 130,
    BusyWoman = 131,
    SexyWoman = 132,
    Pro = 133,
    OldWoman = 134,
    FatWoman = 135,
    JogWoman = 136,
    OldFatWoman = 137,
    Skate = 138,
}, __readonly_table_meta__)

constants.PedFightingStyle = setmetatable({
    Standard = 4,
    Boxing = 5,
    KungFu = 6,
    KneeHead = 7,
    GrabKick = 15,
    Elbows = 16,
}, __readonly_table_meta__)

    )~LUA~";
}