; Do not edit this file manually because it has been generated by generator.cpp

.386
.model flat, stdcall

.code

  extern functions : dword

  __EXPORT__0__ proc  ; CloseDriver @4
    jmp functions[0*4]
  __EXPORT__0__ endp

  __EXPORT__1__ proc  ; DefDriverProc @5
    jmp functions[1*4]
  __EXPORT__1__ endp

  __EXPORT__2__ proc  ; DriverCallback @6
    jmp functions[2*4]
  __EXPORT__2__ endp

  __EXPORT__3__ proc  ; DrvGetModuleHandle @7
    jmp functions[3*4]
  __EXPORT__3__ endp

  __EXPORT__4__ proc  ; GetDriverModuleHandle @8
    jmp functions[4*4]
  __EXPORT__4__ endp

  __EXPORT__5__ proc  ; NotifyCallbackData @9
    jmp functions[5*4]
  __EXPORT__5__ endp

  __EXPORT__6__ proc  ; OpenDriver @10
    jmp functions[6*4]
  __EXPORT__6__ endp

  __EXPORT__7__ proc  ; PlaySound @11
    jmp functions[7*4]
  __EXPORT__7__ endp

  __EXPORT__8__ proc  ; PlaySoundA @12
    jmp functions[8*4]
  __EXPORT__8__ endp

  __EXPORT__9__ proc  ; PlaySoundW @13
    jmp functions[9*4]
  __EXPORT__9__ endp

  __EXPORT__10__ proc  ; SendDriverMessage @14
    jmp functions[10*4]
  __EXPORT__10__ endp

  __EXPORT__11__ proc  ; WOW32DriverCallback @15
    jmp functions[11*4]
  __EXPORT__11__ endp

  __EXPORT__12__ proc  ; WOW32ResolveMultiMediaHandle @16
    jmp functions[12*4]
  __EXPORT__12__ endp

  __EXPORT__13__ proc  ; WOWAppExit @17
    jmp functions[13*4]
  __EXPORT__13__ endp

  __EXPORT__14__ proc  ; aux32Message @18
    jmp functions[14*4]
  __EXPORT__14__ endp

  __EXPORT__15__ proc  ; auxGetDevCapsA @19
    jmp functions[15*4]
  __EXPORT__15__ endp

  __EXPORT__16__ proc  ; auxGetDevCapsW @20
    jmp functions[16*4]
  __EXPORT__16__ endp

  __EXPORT__17__ proc  ; auxGetNumDevs @21
    jmp functions[17*4]
  __EXPORT__17__ endp

  __EXPORT__18__ proc  ; auxGetVolume @22
    jmp functions[18*4]
  __EXPORT__18__ endp

  __EXPORT__19__ proc  ; auxOutMessage @23
    jmp functions[19*4]
  __EXPORT__19__ endp

  __EXPORT__20__ proc  ; auxSetVolume @24
    jmp functions[20*4]
  __EXPORT__20__ endp

  __EXPORT__21__ proc  ; joy32Message @25
    jmp functions[21*4]
  __EXPORT__21__ endp

  __EXPORT__22__ proc  ; joyConfigChanged @26
    jmp functions[22*4]
  __EXPORT__22__ endp

  __EXPORT__23__ proc  ; joyGetDevCapsA @27
    jmp functions[23*4]
  __EXPORT__23__ endp

  __EXPORT__24__ proc  ; joyGetDevCapsW @28
    jmp functions[24*4]
  __EXPORT__24__ endp

  __EXPORT__25__ proc  ; joyGetNumDevs @29
    jmp functions[25*4]
  __EXPORT__25__ endp

  __EXPORT__26__ proc  ; joyGetPos @30
    jmp functions[26*4]
  __EXPORT__26__ endp

  __EXPORT__27__ proc  ; joyGetPosEx @31
    jmp functions[27*4]
  __EXPORT__27__ endp

  __EXPORT__28__ proc  ; joyGetThreshold @32
    jmp functions[28*4]
  __EXPORT__28__ endp

  __EXPORT__29__ proc  ; joyReleaseCapture @33
    jmp functions[29*4]
  __EXPORT__29__ endp

  __EXPORT__30__ proc  ; joySetCapture @34
    jmp functions[30*4]
  __EXPORT__30__ endp

  __EXPORT__31__ proc  ; joySetThreshold @35
    jmp functions[31*4]
  __EXPORT__31__ endp

  __EXPORT__32__ proc  ; mci32Message @36
    jmp functions[32*4]
  __EXPORT__32__ endp

  __EXPORT__33__ proc  ; mciDriverNotify @37
    jmp functions[33*4]
  __EXPORT__33__ endp

  __EXPORT__34__ proc  ; mciDriverYield @38
    jmp functions[34*4]
  __EXPORT__34__ endp

  __EXPORT__35__ proc  ; mciExecute @3
    jmp functions[35*4]
  __EXPORT__35__ endp

  __EXPORT__36__ proc  ; mciFreeCommandResource @39
    jmp functions[36*4]
  __EXPORT__36__ endp

  __EXPORT__37__ proc  ; mciGetCreatorTask @40
    jmp functions[37*4]
  __EXPORT__37__ endp

  __EXPORT__38__ proc  ; mciGetDeviceIDA @41
    jmp functions[38*4]
  __EXPORT__38__ endp

  __EXPORT__39__ proc  ; mciGetDeviceIDFromElementIDA @42
    jmp functions[39*4]
  __EXPORT__39__ endp

  __EXPORT__40__ proc  ; mciGetDeviceIDFromElementIDW @43
    jmp functions[40*4]
  __EXPORT__40__ endp

  __EXPORT__41__ proc  ; mciGetDeviceIDW @44
    jmp functions[41*4]
  __EXPORT__41__ endp

  __EXPORT__42__ proc  ; mciGetDriverData @45
    jmp functions[42*4]
  __EXPORT__42__ endp

  __EXPORT__43__ proc  ; mciGetErrorStringA @46
    jmp functions[43*4]
  __EXPORT__43__ endp

  __EXPORT__44__ proc  ; mciGetErrorStringW @47
    jmp functions[44*4]
  __EXPORT__44__ endp

  __EXPORT__45__ proc  ; mciGetYieldProc @48
    jmp functions[45*4]
  __EXPORT__45__ endp

  __EXPORT__46__ proc  ; mciLoadCommandResource @49
    jmp functions[46*4]
  __EXPORT__46__ endp

  __EXPORT__47__ proc  ; mciSendCommandA @50
    jmp functions[47*4]
  __EXPORT__47__ endp

  __EXPORT__48__ proc  ; mciSendCommandW @51
    jmp functions[48*4]
  __EXPORT__48__ endp

  __EXPORT__49__ proc  ; mciSendStringA @52
    jmp functions[49*4]
  __EXPORT__49__ endp

  __EXPORT__50__ proc  ; mciSendStringW @53
    jmp functions[50*4]
  __EXPORT__50__ endp

  __EXPORT__51__ proc  ; mciSetDriverData @54
    jmp functions[51*4]
  __EXPORT__51__ endp

  __EXPORT__52__ proc  ; mciSetYieldProc @55
    jmp functions[52*4]
  __EXPORT__52__ endp

  __EXPORT__53__ proc  ; mid32Message @56
    jmp functions[53*4]
  __EXPORT__53__ endp

  __EXPORT__54__ proc  ; midiConnect @57
    jmp functions[54*4]
  __EXPORT__54__ endp

  __EXPORT__55__ proc  ; midiDisconnect @58
    jmp functions[55*4]
  __EXPORT__55__ endp

  __EXPORT__56__ proc  ; midiInAddBuffer @59
    jmp functions[56*4]
  __EXPORT__56__ endp

  __EXPORT__57__ proc  ; midiInClose @60
    jmp functions[57*4]
  __EXPORT__57__ endp

  __EXPORT__58__ proc  ; midiInGetDevCapsA @61
    jmp functions[58*4]
  __EXPORT__58__ endp

  __EXPORT__59__ proc  ; midiInGetDevCapsW @62
    jmp functions[59*4]
  __EXPORT__59__ endp

  __EXPORT__60__ proc  ; midiInGetErrorTextA @63
    jmp functions[60*4]
  __EXPORT__60__ endp

  __EXPORT__61__ proc  ; midiInGetErrorTextW @64
    jmp functions[61*4]
  __EXPORT__61__ endp

  __EXPORT__62__ proc  ; midiInGetID @65
    jmp functions[62*4]
  __EXPORT__62__ endp

  __EXPORT__63__ proc  ; midiInGetNumDevs @66
    jmp functions[63*4]
  __EXPORT__63__ endp

  __EXPORT__64__ proc  ; midiInMessage @67
    jmp functions[64*4]
  __EXPORT__64__ endp

  __EXPORT__65__ proc  ; midiInOpen @68
    jmp functions[65*4]
  __EXPORT__65__ endp

  __EXPORT__66__ proc  ; midiInPrepareHeader @69
    jmp functions[66*4]
  __EXPORT__66__ endp

  __EXPORT__67__ proc  ; midiInReset @70
    jmp functions[67*4]
  __EXPORT__67__ endp

  __EXPORT__68__ proc  ; midiInStart @71
    jmp functions[68*4]
  __EXPORT__68__ endp

  __EXPORT__69__ proc  ; midiInStop @72
    jmp functions[69*4]
  __EXPORT__69__ endp

  __EXPORT__70__ proc  ; midiInUnprepareHeader @73
    jmp functions[70*4]
  __EXPORT__70__ endp

  __EXPORT__71__ proc  ; midiOutCacheDrumPatches @74
    jmp functions[71*4]
  __EXPORT__71__ endp

  __EXPORT__72__ proc  ; midiOutCachePatches @75
    jmp functions[72*4]
  __EXPORT__72__ endp

  __EXPORT__73__ proc  ; midiOutClose @76
    jmp functions[73*4]
  __EXPORT__73__ endp

  __EXPORT__74__ proc  ; midiOutGetDevCapsA @77
    jmp functions[74*4]
  __EXPORT__74__ endp

  __EXPORT__75__ proc  ; midiOutGetDevCapsW @78
    jmp functions[75*4]
  __EXPORT__75__ endp

  __EXPORT__76__ proc  ; midiOutGetErrorTextA @79
    jmp functions[76*4]
  __EXPORT__76__ endp

  __EXPORT__77__ proc  ; midiOutGetErrorTextW @80
    jmp functions[77*4]
  __EXPORT__77__ endp

  __EXPORT__78__ proc  ; midiOutGetID @81
    jmp functions[78*4]
  __EXPORT__78__ endp

  __EXPORT__79__ proc  ; midiOutGetNumDevs @82
    jmp functions[79*4]
  __EXPORT__79__ endp

  __EXPORT__80__ proc  ; midiOutGetVolume @83
    jmp functions[80*4]
  __EXPORT__80__ endp

  __EXPORT__81__ proc  ; midiOutLongMsg @84
    jmp functions[81*4]
  __EXPORT__81__ endp

  __EXPORT__82__ proc  ; midiOutMessage @85
    jmp functions[82*4]
  __EXPORT__82__ endp

  __EXPORT__83__ proc  ; midiOutOpen @86
    jmp functions[83*4]
  __EXPORT__83__ endp

  __EXPORT__84__ proc  ; midiOutPrepareHeader @87
    jmp functions[84*4]
  __EXPORT__84__ endp

  __EXPORT__85__ proc  ; midiOutReset @88
    jmp functions[85*4]
  __EXPORT__85__ endp

  __EXPORT__86__ proc  ; midiOutSetVolume @89
    jmp functions[86*4]
  __EXPORT__86__ endp

  __EXPORT__87__ proc  ; midiOutShortMsg @90
    jmp functions[87*4]
  __EXPORT__87__ endp

  __EXPORT__88__ proc  ; midiOutUnprepareHeader @91
    jmp functions[88*4]
  __EXPORT__88__ endp

  __EXPORT__89__ proc  ; midiStreamClose @92
    jmp functions[89*4]
  __EXPORT__89__ endp

  __EXPORT__90__ proc  ; midiStreamOpen @93
    jmp functions[90*4]
  __EXPORT__90__ endp

  __EXPORT__91__ proc  ; midiStreamOut @94
    jmp functions[91*4]
  __EXPORT__91__ endp

  __EXPORT__92__ proc  ; midiStreamPause @95
    jmp functions[92*4]
  __EXPORT__92__ endp

  __EXPORT__93__ proc  ; midiStreamPosition @96
    jmp functions[93*4]
  __EXPORT__93__ endp

  __EXPORT__94__ proc  ; midiStreamProperty @97
    jmp functions[94*4]
  __EXPORT__94__ endp

  __EXPORT__95__ proc  ; midiStreamRestart @98
    jmp functions[95*4]
  __EXPORT__95__ endp

  __EXPORT__96__ proc  ; midiStreamStop @99
    jmp functions[96*4]
  __EXPORT__96__ endp

  __EXPORT__97__ proc  ; mixerClose @100
    jmp functions[97*4]
  __EXPORT__97__ endp

  __EXPORT__98__ proc  ; mixerGetControlDetailsA @101
    jmp functions[98*4]
  __EXPORT__98__ endp

  __EXPORT__99__ proc  ; mixerGetControlDetailsW @102
    jmp functions[99*4]
  __EXPORT__99__ endp

  __EXPORT__100__ proc  ; mixerGetDevCapsA @103
    jmp functions[100*4]
  __EXPORT__100__ endp

  __EXPORT__101__ proc  ; mixerGetDevCapsW @104
    jmp functions[101*4]
  __EXPORT__101__ endp

  __EXPORT__102__ proc  ; mixerGetID @105
    jmp functions[102*4]
  __EXPORT__102__ endp

  __EXPORT__103__ proc  ; mixerGetLineControlsA @106
    jmp functions[103*4]
  __EXPORT__103__ endp

  __EXPORT__104__ proc  ; mixerGetLineControlsW @107
    jmp functions[104*4]
  __EXPORT__104__ endp

  __EXPORT__105__ proc  ; mixerGetLineInfoA @108
    jmp functions[105*4]
  __EXPORT__105__ endp

  __EXPORT__106__ proc  ; mixerGetLineInfoW @109
    jmp functions[106*4]
  __EXPORT__106__ endp

  __EXPORT__107__ proc  ; mixerGetNumDevs @110
    jmp functions[107*4]
  __EXPORT__107__ endp

  __EXPORT__108__ proc  ; mixerMessage @111
    jmp functions[108*4]
  __EXPORT__108__ endp

  __EXPORT__109__ proc  ; mixerOpen @112
    jmp functions[109*4]
  __EXPORT__109__ endp

  __EXPORT__110__ proc  ; mixerSetControlDetails @113
    jmp functions[110*4]
  __EXPORT__110__ endp

  __EXPORT__111__ proc  ; mmDrvInstall @114
    jmp functions[111*4]
  __EXPORT__111__ endp

  __EXPORT__112__ proc  ; mmGetCurrentTask @115
    jmp functions[112*4]
  __EXPORT__112__ endp

  __EXPORT__113__ proc  ; mmTaskBlock @116
    jmp functions[113*4]
  __EXPORT__113__ endp

  __EXPORT__114__ proc  ; mmTaskCreate @117
    jmp functions[114*4]
  __EXPORT__114__ endp

  __EXPORT__115__ proc  ; mmTaskSignal @118
    jmp functions[115*4]
  __EXPORT__115__ endp

  __EXPORT__116__ proc  ; mmTaskYield @119
    jmp functions[116*4]
  __EXPORT__116__ endp

  __EXPORT__117__ proc  ; mmioAdvance @120
    jmp functions[117*4]
  __EXPORT__117__ endp

  __EXPORT__118__ proc  ; mmioAscend @121
    jmp functions[118*4]
  __EXPORT__118__ endp

  __EXPORT__119__ proc  ; mmioClose @122
    jmp functions[119*4]
  __EXPORT__119__ endp

  __EXPORT__120__ proc  ; mmioCreateChunk @123
    jmp functions[120*4]
  __EXPORT__120__ endp

  __EXPORT__121__ proc  ; mmioDescend @124
    jmp functions[121*4]
  __EXPORT__121__ endp

  __EXPORT__122__ proc  ; mmioFlush @125
    jmp functions[122*4]
  __EXPORT__122__ endp

  __EXPORT__123__ proc  ; mmioGetInfo @126
    jmp functions[123*4]
  __EXPORT__123__ endp

  __EXPORT__124__ proc  ; mmioInstallIOProcA @127
    jmp functions[124*4]
  __EXPORT__124__ endp

  __EXPORT__125__ proc  ; mmioInstallIOProcW @128
    jmp functions[125*4]
  __EXPORT__125__ endp

  __EXPORT__126__ proc  ; mmioOpenA @129
    jmp functions[126*4]
  __EXPORT__126__ endp

  __EXPORT__127__ proc  ; mmioOpenW @130
    jmp functions[127*4]
  __EXPORT__127__ endp

  __EXPORT__128__ proc  ; mmioRead @131
    jmp functions[128*4]
  __EXPORT__128__ endp

  __EXPORT__129__ proc  ; mmioRenameA @132
    jmp functions[129*4]
  __EXPORT__129__ endp

  __EXPORT__130__ proc  ; mmioRenameW @133
    jmp functions[130*4]
  __EXPORT__130__ endp

  __EXPORT__131__ proc  ; mmioSeek @134
    jmp functions[131*4]
  __EXPORT__131__ endp

  __EXPORT__132__ proc  ; mmioSendMessage @135
    jmp functions[132*4]
  __EXPORT__132__ endp

  __EXPORT__133__ proc  ; mmioSetBuffer @136
    jmp functions[133*4]
  __EXPORT__133__ endp

  __EXPORT__134__ proc  ; mmioSetInfo @137
    jmp functions[134*4]
  __EXPORT__134__ endp

  __EXPORT__135__ proc  ; mmioStringToFOURCCA @138
    jmp functions[135*4]
  __EXPORT__135__ endp

  __EXPORT__136__ proc  ; mmioStringToFOURCCW @139
    jmp functions[136*4]
  __EXPORT__136__ endp

  __EXPORT__137__ proc  ; mmioWrite @140
    jmp functions[137*4]
  __EXPORT__137__ endp

  __EXPORT__138__ proc  ; mmsystemGetVersion @141
    jmp functions[138*4]
  __EXPORT__138__ endp

  __EXPORT__139__ proc  ; mod32Message @142
    jmp functions[139*4]
  __EXPORT__139__ endp

  __EXPORT__140__ proc  ; mxd32Message @143
    jmp functions[140*4]
  __EXPORT__140__ endp

  __EXPORT__141__ proc  ; sndPlaySoundA @144
    jmp functions[141*4]
  __EXPORT__141__ endp

  __EXPORT__142__ proc  ; sndPlaySoundW @145
    jmp functions[142*4]
  __EXPORT__142__ endp

  __EXPORT__143__ proc  ; tid32Message @146
    jmp functions[143*4]
  __EXPORT__143__ endp

  __EXPORT__144__ proc  ; timeBeginPeriod @147
    jmp functions[144*4]
  __EXPORT__144__ endp

  __EXPORT__145__ proc  ; timeEndPeriod @148
    jmp functions[145*4]
  __EXPORT__145__ endp

  __EXPORT__146__ proc  ; timeGetDevCaps @149
    jmp functions[146*4]
  __EXPORT__146__ endp

  __EXPORT__147__ proc  ; timeGetSystemTime @150
    jmp functions[147*4]
  __EXPORT__147__ endp

  __EXPORT__148__ proc  ; timeGetTime @151
    jmp functions[148*4]
  __EXPORT__148__ endp

  __EXPORT__149__ proc  ; timeKillEvent @152
    jmp functions[149*4]
  __EXPORT__149__ endp

  __EXPORT__150__ proc  ; timeSetEvent @153
    jmp functions[150*4]
  __EXPORT__150__ endp

  __EXPORT__151__ proc  ; waveInAddBuffer @154
    jmp functions[151*4]
  __EXPORT__151__ endp

  __EXPORT__152__ proc  ; waveInClose @155
    jmp functions[152*4]
  __EXPORT__152__ endp

  __EXPORT__153__ proc  ; waveInGetDevCapsA @156
    jmp functions[153*4]
  __EXPORT__153__ endp

  __EXPORT__154__ proc  ; waveInGetDevCapsW @157
    jmp functions[154*4]
  __EXPORT__154__ endp

  __EXPORT__155__ proc  ; waveInGetErrorTextA @158
    jmp functions[155*4]
  __EXPORT__155__ endp

  __EXPORT__156__ proc  ; waveInGetErrorTextW @159
    jmp functions[156*4]
  __EXPORT__156__ endp

  __EXPORT__157__ proc  ; waveInGetID @160
    jmp functions[157*4]
  __EXPORT__157__ endp

  __EXPORT__158__ proc  ; waveInGetNumDevs @161
    jmp functions[158*4]
  __EXPORT__158__ endp

  __EXPORT__159__ proc  ; waveInGetPosition @162
    jmp functions[159*4]
  __EXPORT__159__ endp

  __EXPORT__160__ proc  ; waveInMessage @163
    jmp functions[160*4]
  __EXPORT__160__ endp

  __EXPORT__161__ proc  ; waveInOpen @164
    jmp functions[161*4]
  __EXPORT__161__ endp

  __EXPORT__162__ proc  ; waveInPrepareHeader @165
    jmp functions[162*4]
  __EXPORT__162__ endp

  __EXPORT__163__ proc  ; waveInReset @166
    jmp functions[163*4]
  __EXPORT__163__ endp

  __EXPORT__164__ proc  ; waveInStart @167
    jmp functions[164*4]
  __EXPORT__164__ endp

  __EXPORT__165__ proc  ; waveInStop @168
    jmp functions[165*4]
  __EXPORT__165__ endp

  __EXPORT__166__ proc  ; waveInUnprepareHeader @169
    jmp functions[166*4]
  __EXPORT__166__ endp

  __EXPORT__167__ proc  ; waveOutBreakLoop @170
    jmp functions[167*4]
  __EXPORT__167__ endp

  __EXPORT__168__ proc  ; waveOutClose @171
    jmp functions[168*4]
  __EXPORT__168__ endp

  __EXPORT__169__ proc  ; waveOutGetDevCapsA @172
    jmp functions[169*4]
  __EXPORT__169__ endp

  __EXPORT__170__ proc  ; waveOutGetDevCapsW @173
    jmp functions[170*4]
  __EXPORT__170__ endp

  __EXPORT__171__ proc  ; waveOutGetErrorTextA @174
    jmp functions[171*4]
  __EXPORT__171__ endp

  __EXPORT__172__ proc  ; waveOutGetErrorTextW @175
    jmp functions[172*4]
  __EXPORT__172__ endp

  __EXPORT__173__ proc  ; waveOutGetID @176
    jmp functions[173*4]
  __EXPORT__173__ endp

  __EXPORT__174__ proc  ; waveOutGetNumDevs @177
    jmp functions[174*4]
  __EXPORT__174__ endp

  __EXPORT__175__ proc  ; waveOutGetPitch @178
    jmp functions[175*4]
  __EXPORT__175__ endp

  __EXPORT__176__ proc  ; waveOutGetPlaybackRate @179
    jmp functions[176*4]
  __EXPORT__176__ endp

  __EXPORT__177__ proc  ; waveOutGetPosition @180
    jmp functions[177*4]
  __EXPORT__177__ endp

  __EXPORT__178__ proc  ; waveOutGetVolume @181
    jmp functions[178*4]
  __EXPORT__178__ endp

  __EXPORT__179__ proc  ; waveOutMessage @182
    jmp functions[179*4]
  __EXPORT__179__ endp

  __EXPORT__180__ proc  ; waveOutOpen @183
    jmp functions[180*4]
  __EXPORT__180__ endp

  __EXPORT__181__ proc  ; waveOutPause @184
    jmp functions[181*4]
  __EXPORT__181__ endp

  __EXPORT__182__ proc  ; waveOutPrepareHeader @185
    jmp functions[182*4]
  __EXPORT__182__ endp

  __EXPORT__183__ proc  ; waveOutReset @186
    jmp functions[183*4]
  __EXPORT__183__ endp

  __EXPORT__184__ proc  ; waveOutRestart @187
    jmp functions[184*4]
  __EXPORT__184__ endp

  __EXPORT__185__ proc  ; waveOutSetPitch @188
    jmp functions[185*4]
  __EXPORT__185__ endp

  __EXPORT__186__ proc  ; waveOutSetPlaybackRate @189
    jmp functions[186*4]
  __EXPORT__186__ endp

  __EXPORT__187__ proc  ; waveOutSetVolume @190
    jmp functions[187*4]
  __EXPORT__187__ endp

  __EXPORT__188__ proc  ; waveOutUnprepareHeader @191
    jmp functions[188*4]
  __EXPORT__188__ endp

  __EXPORT__189__ proc  ; waveOutWrite @192
    jmp functions[189*4]
  __EXPORT__189__ endp

  __EXPORT__190__ proc  ; wid32Message @193
    jmp functions[190*4]
  __EXPORT__190__ endp

  __EXPORT__191__ proc  ; wod32Message @194
    jmp functions[191*4]
  __EXPORT__191__ endp

  __EXPORT__192__ proc  ; [NONAME] @2
    jmp functions[192*4]
  __EXPORT__192__ endp

end
