name: Feature request
description: Suggest an idea for this project
labels: enhancement
type: Feature
body:
  - type: markdown
    attributes:
      value: |
        # Stop right now if you're reporting a cheat or security vulnerability!

        **Please read our [Security Policy](https://github.com/multitheftauto/mtasa-blue/security/policy) to learn where to responsibly report security issues. Thank you.**

        This template is only for suggesting features. If you have a bug report, please use the [bug report template](https://github.com/multitheftauto/mtasa-blue/issues/new?assignees=&labels=bug&template=bug_report.yml).
  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: |
        Please provide a clear and concise description of what the problem is. For example: I'm always frustrated when [...]
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: Please provide a clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Please provide a clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        If available, please provide any other additional context, such as screenshots or videos, or links to other relevant issues, pull requests or documents that can help others better understand your request.
  - type: checkboxes
    id: terms
    attributes:
      label: Security Policy
      description: By submitting this issue, you express that you have read and understood our [Security Policy](https://github.com/multitheftauto/mtasa-blue/security/policy) and that this issue is not about a cheat or security vulnerability.
      options:
        - label: I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.
          required: true
