
DECLARE_EASING(Linear)

DECLARE_EASING(InQuad)
DECLARE_EASING(OutQuad)
DECLARE_EASING(InOutQuad)
DECLARE_EASING(OutInQuad)

DECLARE_EASING(InElastic)
DECLARE_EASING(OutElastic)
DECLARE_EASING(InOutElastic)
DECLARE_EASING(OutInElastic)

DECLARE_EASING(InBack)
DECLARE_EASING(OutBack)
DECLARE_EASING(InOutBack)
DECLARE_EASING(OutInBack)

DECLARE_EASING(InBounce)
DECLARE_EASING(OutBounce)
DECLARE_EASING(InOutBounce)
DECLARE_EASING(OutInBounce)

DECLARE_EASING(SineCurve)
DECLARE_EASING(CosineCurve)