/*****************************************************************************
 *
 *  PROJECT:     Multi Theft Auto
 *  LICENSE:     See LICENSE in the top level directory
 *  FILE:        sdk/MarkerSprite.h
 *  PURPOSE:     Header for common definitions
 *
 *  Multi Theft Auto is available from https://www.multitheftauto.com/
 *
 *****************************************************************************/

#pragma once
#include <cstdint>

enum class MarkerSprite : std::uint8_t
{
    MARKER_SPRITE_NONE = 0,
    MARKER_SPRITE_BORDER,
    MARKER_SPRITE_CENTRE,
    MARKER_SPRITE_MAP_HERE,
    MARKER_SPRITE_NORTH,

    MARKER_SPRITE_AIRYARD,
    MARKER_SPRITE_GUN,
    MARKER_SPRITE_BARBERS,
    MARKER_SPRITE_BIG_SMOKE,
    MARKER_SPRITE_BOATYARD,
    MARKER_SPRITE_BURGERSHOT,
    MARKER_SPRITE_BULLDOZER,
    MARKER_SPRITE_CAT_PINK,
    MARKER_SPRITE_CESAR,
    MARKER_SPRITE_CHICKEN,
    MARKER_SPRITE_CJ,
    MARKER_SPRITE_CRASH1,
    MARKER_SPRITE_DINER,
    MARKER_SPRITE_EMMETGUN,
    MARKER_SPRITE_ENEMYATTACK,
    MARKER_SPRITE_FIRE,
    MARKER_SPRITE_GIRLFRIEND,
    MARKER_SPRITE_HOSPITAL,
    MARKER_SPRITE_LOCO,
    MARKER_SPRITE_MADDOG,
    MARKER_SPRITE_MAFIA,
    MARKER_SPRITE_MCSTRAP,
    MARKER_SPRITE_MOD_GARAGE,
    MARKER_SPRITE_OGLOC,
    MARKER_SPRITE_PIZZA,
    MARKER_SPRITE_POLICE,
    MARKER_SPRITE_PROPERTY_GREEN,
    MARKER_SPRITE_PROPERTY_RED,
    MARKER_SPRITE_RACE,
    MARKER_SPRITE_RYDER,
    MARKER_SPRITE_SAVEHOUSE,
    MARKER_SPRITE_SCHOOL,
    MARKER_SPRITE_MYSTERY,
    MARKER_SPRITE_SWEET,
    MARKER_SPRITE_TATTOO,
    MARKER_SPRITE_TRUTH,
    MARKER_SPRITE_WAYPOINT,
    MARKER_SPRITE_TORENO_RANCH,
    MARKER_SPRITE_TRIADS,
    MARKER_SPRITE_TRIADS_CASINO,
    MARKER_SPRITE_TSHIRT,
    MARKER_SPRITE_WOOZIE,
    MARKER_SPRITE_ZERO,
    MARKER_SPRITE_DATE_DISCO,
    MARKER_SPRITE_DATE_DRINK,
    MARKER_SPRITE_DATE_FOOD,
    MARKER_SPRITE_TRUCK,
    MARKER_SPRITE_CASH,
    MARKER_SPRITE_FLAG,
    MARKER_SPRITE_GYM,
    MARKER_SPRITE_IMPOUND,
    MARKER_SPRITE_RUNWAY_LIGHT,
    MARKER_SPRITE_RUNWAY,
    MARKER_SPRITE_GANG_B,
    MARKER_SPRITE_GANG_P,
    MARKER_SPRITE_GANG_Y,
    MARKER_SPRITE_GANG_N,
    MARKER_SPRITE_GANG_G,
    MARKER_SPRITE_SPRAY
};
