/*****************************************************************************
 *
 *  PROJECT:     Multi Theft Auto
 *  LICENSE:     See LICENSE in the top level directory
 *  FILE:        sdk/RadarSprite.h
 *  PURPOSE:     Header for common definitions
 *
 *  Multi Theft Auto is available from https://www.multitheftauto.com/
 *
 *****************************************************************************/

#pragma once

enum class RadarSprite : std::uint8_t
{
    RADAR_SPRITE_NONE = 0,
    RADAR_SPRITE_BORDER,
    RADAR_SPRITE_CENTRE,
    RADAR_SPRITE_MAP_HERE,
    RADAR_SPRITE_NORTH,

    RADAR_SPRITE_AIRYARD,
    RADAR_SPRITE_GUN,
    RADAR_SPRITE_BARBERS,
    RADAR_SPRITE_BIG_SMOKE,
    RADAR_SPRITE_BOATYARD,
    RADAR_SPRITE_BURGERSHOT,
    RADAR_SPRITE_BULLDOZER,
    RADAR_SPRITE_CAT_PINK,
    RADAR_SPRITE_CESAR,
    RADAR_SPRITE_CHICKEN,
    RADAR_SPRITE_CJ,
    RADAR_SPRITE_CRASH1,
    RADAR_SPRITE_DINER,
    RADAR_SPRITE_EMMETGUN,
    RADAR_SPRITE_ENEMYATTACK,
    RADAR_SPRITE_FIRE,
    RADAR_SPRITE_GIRLFRIEND,
    RADAR_SPRITE_HOSPITAL,
    RADAR_SPRITE_LOCO,
    RADAR_SPRITE_MADDOG,
    RADAR_SPRITE_MAFIA,
    RADAR_SPRITE_MCSTRAP,
    RADAR_SPRITE_MOD_GARAGE,
    RADAR_SPRITE_OGLOC,
    RADAR_SPRITE_PIZZA,
    RADAR_SPRITE_POLICE,
    RADAR_SPRITE_PROPERTY_GREEN,
    RADAR_SPRITE_PROPERTY_RED,
    RADAR_SPRITE_RACE,
    RADAR_SPRITE_RYDER,
    RADAR_SPRITE_SAVEHOUSE,
    RADAR_SPRITE_SCHOOL,
    RADAR_SPRITE_MYSTERY,
    RADAR_SPRITE_SWEET,
    RADAR_SPRITE_TATTOO,
    RADAR_SPRITE_TRUTH,
    RADAR_SPRITE_WAYPOINT,
    RADAR_SPRITE_TORENO_RANCH,
    RADAR_SPRITE_TRIADS,
    RADAR_SPRITE_TRIADS_CASINO,
    RADAR_SPRITE_TSHIRT,
    RADAR_SPRITE_WOOZIE,
    RADAR_SPRITE_ZERO,
    RADAR_SPRITE_DATE_DISCO,
    RADAR_SPRITE_DATE_DRINK,
    RADAR_SPRITE_DATE_FOOD,
    RADAR_SPRITE_TRUCK,
    RADAR_SPRITE_CASH,
    RADAR_SPRITE_FLAG,
    RADAR_SPRITE_GYM,
    RADAR_SPRITE_IMPOUND,
    RADAR_SPRITE_RUNWAY_LIGHT,
    RADAR_SPRITE_RUNWAY,
    RADAR_SPRITE_GANG_B,
    RADAR_SPRITE_GANG_P,
    RADAR_SPRITE_GANG_Y,
    RADAR_SPRITE_GANG_N,
    RADAR_SPRITE_GANG_G,
    RADAR_SPRITE_SPRAY
};
