/*****************************************************************************
*
*  PROJECT:     Multi Theft Auto v1.0
*  LICENSE:     See LICENSE in the top level directory
*  FILE:        mods/deathmatch/logic/CResourceFile.h
*  PURPOSE:     Resource server-side file item class
*  DEVELOPERS:  Ed Lyons <>
*               Jax <>
*               Chris McArthur <>
*               Christian Myhre Lundheim <>
*
*  Multi Theft Auto is available from http://www.multitheftauto.com/
*
*****************************************************************************/

// This class controls a single resource file. This could be
// any item contained within the resource, mainly being a
// map or script.

// This is just a base class.

class CResourceFile;

#ifndef CRESOURCEFILE_H
#define CRESOURCEFILE_H
#include <string.h>
#include "ehs/ehs.h"

class CResourceFile
{
public:
    enum eResourceType
    {
        RESOURCE_FILE_TYPE_MAP,
        RESOURCE_FILE_TYPE_SCRIPT,
        RESOURCE_FILE_TYPE_CLIENT_SCRIPT,
        RESOURCE_FILE_TYPE_CONFIG,
        RESOURCE_FILE_TYPE_CLIENT_CONFIG,
        RESOURCE_FILE_TYPE_HTML,
        RESOURCE_FILE_TYPE_CLIENT_FILE,
        RESOURCE_FILE_TYPE_NONE,
    }; // TODO: sort all client-side enums and use >= (instead of each individual type) on comparisons that use this enum?

protected:
    class CResource *           m_resource;
    char *                      m_szResourceFileName; // full path
    char *                      m_szShortName; // just the filename
    char *                      m_szWindowsName; // the name with backwards slashes
    eResourceType               m_type;
    class CLuaMain *            m_pVM;
    unsigned long               m_ulCRC; // CRC last time this was loaded, generated by GenerateCRC()
    
public:
                                CResourceFile ( class CResource * resource, const char* szShortName, const char* szResourceFileName );
    virtual                     ~CResourceFile ( void );

    virtual ResponseCode        Request ( HttpRequest * ipoHttpRequest, HttpResponse * ipoHttpResponse );

    virtual bool                Start ( void ) = 0;
    virtual bool                Stop ( void ) = 0;

    inline eResourceType        GetType() { return m_type; }
    inline char *               GetPath() { return m_szResourceFileName; }
    inline char *               GetName() { return m_szShortName; }
    inline char *               GetWindowsName() { return m_szWindowsName; }

    inline unsigned long        GetLastCRC ( void ) { return m_ulCRC; }
    void                        SetLastCRC ( unsigned long ulCRC ) { m_ulCRC = ulCRC; }

    double                      GetSize ( void );
};

#endif
